---
name: release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/go

      - name: Container Image
        uses: ./.github/actions/buildah
        with:
          tags: "latest,${{ github.ref }}"
          IMAGE_REPO_PASSWORD: ${{ secrets.GITHUB_TOKEN }}

      - name: GitHub Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
        run: |
          make github-release
